import { createContext, useContext, useState, ReactNode } from "react";

type Language = "fr" | "ku";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.activities": "Activités",
    "nav.courses": "Cours de langues",
    "nav.about": "À propos",
    "nav.name.top": "Association Culturelle",
    "nav.name.bottom": "Kurde de Genève",
    
    // Home
    "home.title": "ASSOCIATION CULTURELLE KURDE DE GENÈVE",
    "home.subtitle": "Pour diffuser la culture kurde en Suisse",
    "home.mission.title": "Notre mission",
    "home.mission.culture.title": "Connaissance du peuple kurde",
    "home.mission.culture.desc": "La possibilité de faire connaître le peuple kurde à toutes les religions et cultures, et d’unir les Kurdes dans la société suisse.",
    "home.mission.language.title": "Apprentissage de la langue",
    "home.mission.language.desc": "L'apprentissage de la langue kurde, en particulier pour les membres de la communauté kurde en Suisse. Les cours sont dispensés par des enseignants kurdes expérimentés.",
    "home.mission.activities.title": "Paix",
    "home.mission.activities.desc": "L'objectif est d'aider les personnes de différentes communautés en Suisse à se comprendre et à s'entendre, entre autre grâce à l'organisation d'événements culturels et sociaux.",
    "home.courses.title": "Cours de langue Kurde",
    "home.courses.desc": "Aux honorables parents de notre communauté kurde à Genève, nous vous invitons à inscrire vos enfants à l'inscription entre 6 et 12 ans sur le site officiel d'enseignement des langues maternelles (dont la couleur kurde) à Genève par reconnaissance devant la Direction de l'Intégration à Genève.\n\nCet enregistrement vise à aider vos enfants à mieux apprendre leur langue maternelle. Pour plus d'informations, veuillez contacter l'Association Culturelle Kurde à Genève via l'adresse e-mail ou le numéro de téléphone fournis sur le site.",
    "home.courses.button": "En savoir plus",
    "home.support.title": "Soutenir la diffusion de la culture kurde",
    "home.support.desc": "Votre soutien nous aide à continuer notre mission de préservation et de diffusion de la culture kurde en Suisse. Chaque contribution fait la différence.",
    "home.support.button": "Faire un don",
    "home.princess.pre-title": "Visite du directeur de ACKG",
    "home.princess.title": "chez la princesse kurde Sînem Khan",
    "home.princess.desc": "Je la remercie en mon nom et au nom de tous les membres de l'Association Culturelle Kurde de Genève, pour son chaleureux accueil. Je lui souhaite santé, succès et longue vie.",
    "home.princess.signature": "M. Aziz Kalo",
    "home.activities.title": "Nos Activités",
    "home.activities.viewAll": "Voir toutes",
    "home.activities.desc": "Nous organisons de nombreuses activités, ouvertes à tous!",
    "home.activities.none": "Aucune activité disponible pour le moment. Revenez bientôt!",
    
    // Activities
    "activities.title": "Nos activités",
    "activities.search": "Rechercher une activité...",
    "activities.none": "Aucune activité disponible pour le moment.",
    "activities.noresults": "Aucune activité trouvée pour votre recherche.",
    "activities.date": "Date de l'activité:",
    "activities.location": "Lieu de l'activité:",
    
    // Activity Detail
    "activity.back": "Retour aux activités",
    "activity.share": "Partager",
    "activity.copied": "Lien copié dans le presse-papier!",
    
    // Courses
    "courses.title": "Cours de langue Kurde",
    "courses.subtitle": "Préservons ensemble notre langue et notre culture",
    "courses.desc": "Découvrez nos cours de langue kurde pour enfants",
    "courses.alphabet": "L'alphabet Kurde-Kurmandji",
    "courses.alphabet.desc": "L’Association de la culture kurde a remis l’alphabet kurde à la Croix-Rouge suisse à Genève. \nLe représentant de l’Association de la culture kurde à Genève, M. Aziz Kalo, s’est rendu au siège de la Croix-Rouge suisse le 8 avril 2019. Lors de sa visite, Kalo a remis une carte des lettres de la langue kurde et leur phonétique au représentants de l’organisation. \nDe leur côté, les représentants de la Croix-Rouge ont exprimé leurs chaleureux remerciements et leur approbation pour cette initiative intellectuelle, et la plaque a été placée dans le coffre de l’exposition spéciale de l’Alphabet des langues du monde. \nIl convient de mentionner que la Croix-Rouge suisse a mis en place une exposition spéciale pour les alphabets des langues du monde à Genève.",
    "courses.info.title": "Informations sur les cours",
    "courses.info.children": "Cours pour enfants (5-12 ans)",
    "courses.info.teens": "Cours pour adolescents (13-17 ans)",
    "courses.info.adults": "Cours pour adultes",
    "courses.info.desc": "Nos cours sont dispensés par des enseignants kurdes expérimentés qui ont à cœur de transmettre la richesse de notre langue et de notre culture.",
    "courses.schedule.title": "Horaires des cours",
    "courses.schedule.children": "Enfants : Mercredi 14h-16h",
    "courses.schedule.teens": "Adolescents : Mercredi 16h-18h",
    "courses.schedule.adults": "Adultes : Samedi 10h-12h",
    "courses.cards.schedule.title": "Horaires flexibles",
    "courses.cards.schedule.desc": "Cours disponibles en semaine et le weekend",
    "courses.cards.groups.title": "Petits groupes",
    "courses.cards.groups.desc": "Maximum 12 élèves par classe",
    "courses.cards.duration.title": "1h30 par cours",
    "courses.cards.duration.desc": "Sessions intensives et efficaces",
    "courses.cards.location.title": "Centre-ville",
    "courses.cards.location.desc": "Facilement accessible en transport",
    "courses.register": "S'inscrire aux cours",
    
    // About
    "about.title": "À propos de l'ACKG",
    "about.mission.title": "Notre mission",
    "about.mission.desc": "L’Association culturelle kurde de Genève (ACKG) est une organisation culturelle bénévole qui s’efforce de promouvoir la culture kurde, de renforcer les liens culturels entre les Suisses et les Kurdes et de sensibiliser à l’usage de la langue kurde dans la société en proposant des cours d’apprentissage du kurde pour enfants et adultes.\nL’association s’efforce de renforcer la compréhension et la coopération entre les différentes cultures, et d’encourager la diversité culturelle et linguistique en Suisse.\nElle travaille également à renforcer les relations entre les membres de la communauté kurde, la cohésion sociale et à protéger les valeurs communautaires, en organisant des activités culturelles, sociales et de divertissement, telles que des expositions d’art, des concerts, des conférences, des discussions et d’autres activités culturelles.",
    "about.values.title": "Nos valeurs",
    "about.values.culture": "Préservation culturelle",
    "about.values.culture.desc": "Maintenir vivantes les traditions, la langue et les valeurs kurdes pour les générations futures",
    "about.values.education": "Éducation et transmission",
    "about.values.education.desc": "Promouvoir les échanges culturels entre la communauté kurde et la société suisse",
    "about.values.solidarity": "Solidarité communautaire",
    "about.values.solidarity.desc": "Accompagner l'intégration des Kurdes en Suisse tout en préservant leur identité culturelle",
    "about.team.title": "Notre équipe",
    "about.contact.title": "Nous contacter",
    "about.contact.email": "Email",
    "about.contact.phone": "Téléphone",
    "about.contact.address": "Adresse",
    
    // Admin
    "admin.title": "Administration ACKG",
    "admin.username": "Nom d'utilisateur",
    "admin.password": "Mot de passe",
    "admin.login": "Se connecter",
    "admin.logout": "Déconnexion",
    "admin.success": "Connexion réussie!",
    "admin.error": "Identifiants incorrects",
    "admin.settings.title": "Paramètres du compte",
    "admin.settings.change": "Changer les identifiants",
    "admin.settings.newUsername": "Nouveau nom d'utilisateur",
    "admin.settings.newPassword": "Nouveau mot de passe",
    "admin.settings.save": "Enregistrer",
    "admin.settings.saved": "Identifiants mis à jour",
    "admin.addActivity.title": "Ajouter une activité",
    "admin.editActivity.title": "Modifier une activité",
    "admin.activity.title": "Titre de l'activité",
    "admin.activity.date": "Date de l'activité",
    "admin.activity.location": "Lieu de l'activité",
    "admin.activity.content": "Contenu",
    "admin.activity.images": "Images",
    "admin.activity.addImages": "Ajouter des images",
    "admin.activity.add": "Ajouter l'activité",
    "admin.activity.update": "Mettre à jour l'activité",
    "admin.activity.added": "Activité ajoutée avec succès!",
    "admin.activity.updated": "Activité mise à jour avec succès!",
    "admin.activity.deleted": "Activité supprimée",
    "admin.activity.deleteConfirm": "Êtes-vous sûr de vouloir supprimer cette activité ?",
    "admin.activity.fillAll": "Veuillez remplir tous les champs",
    "admin.activities.title": "Activités existantes",
    "admin.activities.none": "Aucune activité pour le moment",
    "admin.password.current": "Mot de passe actuel",
    "admin.password.new": "Nouveau mot de passe",
    "admin.password.confirm": "Confirmer le mot de passe",
    "admin.password.change": "Changer le mot de passe",
    "admin.password.changed": "Mot de passe modifié avec succès!",
    "admin.password.mismatch": "Les mots de passe ne correspondent pas",
    "admin.password.forgot": "Mot de passe oublié?",
    "admin.password.reset": "Réinitialiser le mot de passe",
    "admin.password.resetSent": "Email de réinitialisation envoyé!",
    "admin.user.add": "Ajouter un utilisateur admin",
    "admin.user.email": "Email",
    "admin.user.added": "Utilisateur ajouté avec succès!",
    "admin.activity.dateFilter": "Filtrer par date",
    "admin.activity.selectDate": "Sélectionner une date",
    "admin.activity.clearDate": "Effacer la date",
    
    // Footer
    "footer.description": "Association Culturelle Kurde de Genève",
    "footer.contact": "Contact",
    "footer.phone": "Téléphone",
    "footer.email": "Email",
    "footer.legal": "Informations légales",
    "footer.mentions": "Mentions légales",
    "footer.about": "À propos",
    "footer.copyright": "Tous droits réservés",
    
    // Legal
    "legal.title": "Mentions légales",
    "legal.association.title": "Association",
    "legal.association.name": "Nom de l'association",
    "legal.association.address": "Adresse du siège",
    "legal.association.phone": "Téléphone",
    "legal.association.email": "Email",
    "legal.editor.title": "Responsable de la publication",
    "legal.hosting.title": "Hébergement",
    "legal.hosting.provider": "Hébergeur",
    "legal.data.title": "Données personnelles",
    "legal.data.content": "Les données personnelles collectées via ce site sont uniquement utilisées dans le cadre des activités de l'association et ne sont jamais transmises à des tiers. Conformément à la loi fédérale sur la protection des données (LPD), vous disposez d'un droit d'accès, de rectification et de suppression de vos données personnelles.",
    "legal.cookies.title": "Cookies",
    "legal.cookies.content": "Ce site n'utilise pas de cookies de traçage. Seuls des cookies techniques nécessaires au fonctionnement du site peuvent être utilisés.",
    "legal.property.title": "Propriété intellectuelle",
    "legal.property.content": "L'ensemble du contenu de ce site (textes, images, logos) est la propriété de l'Association Culturelle Kurde de Genève. Toute reproduction ou utilisation sans autorisation est interdite.",
    "legal.liability.title": "Limitation de responsabilité",
    "legal.liability.content": "L'ACKG s'efforce de maintenir les informations de ce site à jour et exactes. Toutefois, l'association ne peut être tenue responsable des erreurs, omissions ou résultats obtenus suite à l'utilisation de ces informations.",
  },
  ku: {
    // Navigation
    "nav.home": "Bi xêr hatî",
    "nav.activities": "Çalakiyên me",
    "nav.courses": "Kursa zimane kurdi",
    "nav.about": "Ji dor",
    "nav.name.top": "Komeleya Kultûrê",
    "nav.name.bottom": "Kurdî li Cinêvê",
    
    // Home
    "home.title": "Komela Kultûrê Kurdî li Cinêvê",
    "home.subtitle": "Ji bo pêşxistina çanda Kurdî li Swîsreyê",
    "home.mission.title": "Mîsyona me",
    "home.mission.culture.title": "Zanîna gelê Kurd",
    "home.mission.culture.desc": "Derfetek ji bo naskirina gelê Kurd ji bo hemû ol û çandan, û yekkirina Kurdan di civaka Swîsreyê de.",
    "home.mission.language.title": "Zimanê Kurdî",
    "home.mission.language.desc": "Fêrbûna zimanê Kurdî, bi taybetî ji bo endamên civaka Kurd li Swîsreyê. Qurs ji hêla mamosteyên Kurdî yên xwedî ezmûn ve têne dayîn.",
    "home.mission.activities.title": "Aştiyê",
    "home.mission.activities.desc": "Armanc ew e ku bi rêya organîzekirina çalakiyên çandî û civakî, alîkariya mirovên ji civakên cuda yên li Swîsreyê were kirin da ku hevdu fêm bikin û bi hev re li hev bikin.",
    "home.courses.title": "Kursa zimanê kurdî",
    "home.courses.desc": "Ji bo dê û bavên rêzdar ên civaka me ya Kurd li Cenevreyê, em we vedixwînin ku zarokên xwe yên di navbera 6 û 12 salî de li ser malpera fermî ya perwerdehiya zimanê dayikê (di nav de Kurdî jî) li Cenevreyê qeyd bikin, wekî nîşanek spasdariyê ji bo Rêveberiya Entegrasyonê ya Cenevreyê.\n\nArmanca vê qeydkirinê ew e ku alîkariya zarokên we bike ku zimanê xwe yê dayikê çêtir fêr bibin. Ji bo bêtir agahdarî, ji kerema xwe bi rêya navnîşana e-nameyê an jî jimara têlefonê ya ku li ser malperê hatî dayîn bi Komeleya Çandî ya Kurd li Cenevreyê re têkilî daynin.",
    "home.courses.button": "Zêdetir bizanin",
    "home.support.title": "",
    "home.support.desc": "",
    "home.support.button": "",
    "home.princess.title": "li cem şahzadeya kurd Sînem Xan",
    "home.princess.pre-title": "Serdana rêveberê ACKG",
    "home.princess.desc": "Ez bi navê xwe û bi navê hemû endamên Komeleya Çandî ya Kurd a Cenevreyê ji bo pêşwaziya wê ya germ spasiya wê dikim. Ez ji bo wê tenduristî, serkeftin û temenekî dirêj dixwazim.",
    "home.princess.button": "",
    "home.princess.signature": "M. Aziz Kalo",
    "home.activities.title": "Çalakiyên me",
    "home.activities.viewAll": "Hemî bibînin",
    "home.activities.desc": "Em gelek çalakiyan li dar dixin, ji bo her kesî vekirî ye!",
    "home.activities.none": "Niha ti çalakî tune ne. Ji kerema xwe di demek nêzîk de vegerin!",
    
    // Activities
    "activities.title": "Çalakiyên me",
    "activities.search": "Li çalakiyekê bigere...",
    "activities.none": "Niha ti çalakî tune ne.",
    "activities.noresults": "Ji bo lêgerînê ti çalakî nehat dîtin.",
    "activities.date": "Dîroka çalakîyê:",
    "activities.location": "Cîhê çalakîyê:",

    // Activity Detail
    "activity.back": "Vegere Çalakiyên Me",
    "activity.share": "Parvekirin",
    "activity.copied": "Girêdan hate kopîkirin!",
    
    // Courses
    "courses.title": "وانەی زمانی کوردی",
    "courses.desc": "وانەکانی زمانی کوردیمان بۆ منداڵان و گەورەکان بدۆزەرەوە",
    "courses.subtitle": "با پێکەوە زمان و کولتوورمان بپارێزین",
    "courses.alphabet": "ئەلفوبێی کوردی-کوردمانجی",
    "courses.alphabet.desc": "کۆمەڵەی کولتووری کوردی ئەلفوبێی کوردی بۆ سوپاسگوزاریی سەرخۆشەویستی سویسری لە ژنێڤ پێشکەش کرد. \nنوێنەری کۆمەڵەی کولتووری کوردی لە ژنێڤ، مەلا عەزیز کەلو، ڕۆژی ٨ی نیسانی ٢٠١٩ سەردانی ناوەندی سوپاسگوزاریی سەرخۆشەویستی سویسری کرد. لە کاتی سەردانەکەیدا، کەلو کارتی پیتەکانی زمانى کوردی و فۆنێتیکى ئەوان بۆ نوێنەرانی ڕێکخراوەکە پ ێشکەش کرد. \nلە لایەن خۆیانەوە، نوێنەرانی سوپاسگوزاریی سەرخۆشەویستی سویسری سوپاسگوزاریی گەرم و پەسەندکردنیان بۆ ئەم هەوڵی زانستییە ڕوونکردنەوە و پلیتەکە لە ناو خزانی نیشاندانی تایبەتی ئەلفوبێی زمانە جیهانییەکان دانرا.",
    "courses.info.title": "زانیاری دەربارەی وانەکان",
    "courses.info.children": "وانە بۆ منداڵان (٥-١٢ ساڵ)",
    "courses.info.teens": "وانە بۆ لاوان (١٣-١٧ ساڵ)",
    "courses.info.adults": "وانە بۆ گەورەکان",
    "courses.info.desc": "وانەکانمان لەلایەن مامۆستایانی کوردی بە ئەزموونەوە پێشکەش دەکرێن کە دڵسۆزن لە گەیاندنی دەوڵەمەندی زمان و کولتوورمان.",
    "courses.schedule.title": "کاتی وانەکان",
    "courses.schedule.children": "منداڵان: چوارشەممە ٢-٤ی دوای نیوەڕۆ",
    "courses.schedule.teens": "لاوان: چوارشەممە ٤-٦ی دوای نیوەڕۆ",
    "courses.schedule.adults": "گەورەکان: شەممە ١٠-١٢ی بەیانی",
    "courses.cards.schedule.title": "کاتی گونجاو",
    "courses.cards.schedule.desc": "وانەکان بەردەستە لە هەفتە و کۆتایی هەفتە",
    "courses.cards.groups.title": "کۆمەڵە بچووک",
    "courses.cards.groups.desc": "زیاترین ژمارەی قوتابی لە هەر کلاسیەکدا ١٢یە",
    "courses.cards.duration.title": "١ کاتژمێر و نیوە",
    "courses.cards.duration.desc": "کۆرسە کاتییەکان و کاریگەرییەکان",
    "courses.cards.location.title": "ناوچەی ناو شار",
    "courses.cards.location.desc": "ئاسان بە گەیشتن بە هاتوچۆ",
    "courses.register": "تۆمارکردن لە وانەکان",
    
    // About
    "about.title": "دەربارەی ACKG",
    "about.mission.title": "ئەرکی ئێمە",
    "about.mission.desc": "کۆمەڵەی کولتووری کوردیی ژنێڤ (ACKG) ئەرکی ئەوەی هەیە کە بەهاکانی کوردی بپارێزێت و بەرگری لێ بکات و پەرەی پێبدات، لەهەمان کاتدا یارمەتی یەکخستنی کوردان بدات لە کۆمەڵگای سویسری.",
    "about.values.title": "بەهاکانی ئێمە",
    "about.values.culture": "پاراستنی کولتووری",
    "about.values.culture.desc": "بەهەموو نەوەیەکاندا ڕێگە بدەین بۆ ژیانی بەهاکانی کوردی، زمان و ڕەوشەکان",
    "about.values.education": "پەروەردە و گەیاندن",
    "about.values.education.desc": "پەیوەندییەکانی کولتووری نێوان کۆمەڵگای کوردی و کۆمەڵگای سویسری پەرەپێدەکەین",
    "about.values.solidarity": "یەکڕیزی کۆمەڵایەتی",
    "about.values.solidarity.desc": "یارمەتی یەکخستنی کوردان لە سویسرا بدەین هەروەها بەهاکانی کولتووریان پارێزراو بێت",
    "about.team.title": "تیمەکەمان",
    "about.contact.title": "پەیوەندیکردن",
    "about.contact.email": "ئیمەیڵ",
    "about.contact.phone": "تەلەفۆن",
    "about.contact.address": "ناونیشان",
    
    // Admin
    "admin.title": "بەڕێوەبردنی ACKG",
    "admin.username": "ناوی بەکارهێنەر",
    "admin.password": "وشەی تێپەڕ",
    "admin.login": "چوونەژوورەوە",
    "admin.logout": "چوونەدەرەوە",
    "admin.success": "چوونەژوورەوە سەرکەوتوو بوو!",
    "admin.error": "ناسنامە هەڵەیە",
    "admin.settings.title": "ڕێکخستنەکانی هەژمار",
    "admin.settings.change": "گۆڕینی ناسنامە",
    "admin.settings.newUsername": "ناوی بەکارهێنەری نوێ",
    "admin.settings.newPassword": "وشەی تێپەڕی نوێ",
    "admin.settings.save": "پاشەکەوتکردن",
    "admin.settings.saved": "ناسنامە نوێکرایەوە",
    "admin.addActivity.title": "زیادکردنی چالاکی",
    "admin.editActivity.title": "دەستکاریکردنی چالاکی",
    "admin.activity.title": "ناونیشانی چالاکی",
    "admin.activity.date": "بەرواری چالاکی",
    "admin.activity.location": "شوێنی چالاکی",
    "admin.activity.content": "ناوەڕۆک",
    "admin.activity.images": "وێنەکان",
    "admin.activity.addImages": "زیادکردنی وێنە",
    "admin.activity.add": "زیادکردنی چالاکی",
    "admin.activity.update": "نوێکردنەوەی چالاکی",
    "admin.activity.added": "چالاکی بە سەرکەوتوویی زیادکرا!",
    "admin.activity.updated": "چالاکی بە سەرکەوتوویی نوێکرایەوە!",
    "admin.activity.deleted": "چالاکی سڕایەوە",
    "admin.activity.deleteConfirm": "دڵنیای کە دەتەوێت ئەم چالاکییە بسڕیتەوە؟",
    "admin.activity.fillAll": "تکایە هەموو خانەکان پڕبکەرەوە",
    "admin.activities.title": "چالاکییە بوونەکان",
    "admin.activities.none": "هیچ چالاکییەک لە ئێستادا",
    "admin.password.current": "وشەی تێپەڕی ئێستا",
    "admin.password.new": "وشەی تێپەڕی نوێ",
    "admin.password.confirm": "دووپاتکردنەوەی وشەی تێپەڕ",
    "admin.password.change": "گۆڕینی وشەی تێپەڕ",
    "admin.password.changed": "وشەی تێپەڕ بە سەرکەوتوویی گۆڕدرا!",
    "admin.password.mismatch": "وشەی تێپەڕەکان یەکناگرنەوە",
    "admin.password.forgot": "وشەی تێپەڕت لەبیرچووە؟",
    "admin.password.reset": "دووبارە ڕێکخستنەوەی وشەی تێپەڕ",
    "admin.password.resetSent": "ئیمەیڵی دووبارە ڕێکخستنەوە نێردرا!",
    "admin.user.add": "زیادکردنی بەکارهێنەری بەڕێوەبەر",
    "admin.user.email": "ئیمەیڵ",
    "admin.user.added": "بەکارهێنەر بە سەرکەوتوویی زیادکرا!",
    "admin.activity.dateFilter": "پاڵاوتن بە بەروار",
    "admin.activity.selectDate": "هەڵبژاردنی بەروار",
    "admin.activity.clearDate": "سڕینەوەی بەروار",
    
    // Footer
    "footer.description": "Komela Kultûrê Kurdî li Cinêvê",
    "footer.contact": "Têkelî",
    "footer.phone": "تەلەفۆن",
    "footer.email": "ئیمەیڵ",
    "footer.legal": "Agahiyên qanûnî",
    "footer.mentions": "Daxuyaniya qanûnî",
    "footer.about": "Ji dor",
    "footer.association": "Komela Kultûrê Kurdî li Cinêvê",
    "footer.copyright": "Hemû maf parastî ne",
    
    // Legal
    "legal.title": "باسکردنی یاسایی",
    "legal.association.title": "کۆمەڵە",
    "legal.association.name": "ناوی کۆمەڵە",
    "legal.association.address": "ناونیشانی بنکە",
    "legal.association.phone": "تەلەفۆن",
    "legal.association.email": "ئیمەیڵ",
    "legal.editor.title": "بەرپرسی بڵاوکردنەوە",
    "legal.hosting.title": "میوانداری",
    "legal.hosting.provider": "میواندار",
    "legal.data.title": "زانیاری تایبەت",
    "legal.data.content": "زانیاری تایبەتی کۆکراوە لە ڕێگەی ئەم ماڵپەڕەوە تەنها بەکاردێت لە چوارچێوەی چالاکییەکانی کۆمەڵە و هەرگیز نادرێتە لایەنی سێیەم. بەپێی یاسای فیدراڵی پاراستنی داتا (LPD)، تۆ مافی دەستگەیشتن، ڕاستکردنەوە و سڕینەوەی زانیاریە تایبەتەکانت هەیە.",
    "legal.cookies.title": "کووکیز",
    "legal.cookies.content": "ئەم ماڵپەڕە کووکیی شوێنکەوتن بەکارناهێنێت. تەنها کووکیی تەکنیکی پێویست بۆ کارکردنی ماڵپەڕەکە دەکرێت بەکاربهێنرێت.",
    "legal.property.title": "موڵکی هونەری",
    "legal.property.content": "هەموو ناوەڕۆکی ئەم ماڵپەڕە (دەق، وێنە، لۆگۆ) موڵکی کۆمەڵەی کولتووری کوردیی ژنێڤە. هەر بەرهەمهێنانەوە یان بەکارهێنانێک بەبێ ڕێپێدان قەدەغەیە.",
    "legal.liability.title": "سنووردارکردنی بەرپرسیارێتی",
    "legal.liability.content": "ACKG هەوڵدەدات زانیاریەکانی ئەم ماڵپەڕە نوێ و دروست ڕابگرێت. بەڵام، کۆمەڵە ناتوانرێت بەرپرسیار بگیرێت بۆ هەڵە، لابردن یان ئەنجامەکانی بەدەستهاتوو دوای بەکارهێنانی ئەم زانیاریانە.",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("fr");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
